FROM python:3.9-slim

WORKDIR /app

COPY requirements/dev.txt ./requirements/

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        tzdata \
        bash \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade --no-cache-dir pip
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install --force-reinstall --no-cache-dir -r requirements/dev.txt

CMD ["bash", "-c", "flask run --host=0.0.0.0 --port=5000 --reload & celery -A wsgi.celery worker --loglevel=info --autoscale=10,2 && wait"]
