FROM python:3.9-slim

WORKDIR /app

COPY requirements/prod.txt ./requirements/

RUN apt-get update && \
    apt-get install -y --no-install-recommends bash tzdata && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade --no-cache-dir pip
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install --force-reinstall --no-cache-dir -r requirements/prod.txt

COPY . .

CMD ["bash", "-c", "gunicorn -c gunicorn_config.py wsgi:app & celery -A wsgi.celery worker --loglevel=info --autoscale=9,2 && wait"]
