FROM python:3.9-slim

WORKDIR /app

COPY requirements/*.txt ./requirements/
RUN apt-get update && apt-get install -y tzdata
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade --no-cache-dir pip
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install --no-cache-dir -r requirements/dev.txt

COPY . .

CMD flask run --host=0.0.0.0 --port=5000 --reload & celery -A wsgi.celery worker --loglevel=info --autoscale=10,2
